/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ProjectUAS;
import com.itextpdf.kernel.colors.ColorConstants;
import com.itextpdf.kernel.colors.DeviceRgb;
import com.itextpdf.kernel.geom.PageSize;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Cell;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Table;
import com.itextpdf.layout.properties.TextAlignment;
import com.itextpdf.layout.properties.VerticalAlignment;
import com.itextpdf.layout.borders.Border;
import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author Kelua
 */
public class Pelanggan extends javax.swing.JFrame {
    
        


    /**
     * Creates new form Daftaruser
     */

    public Pelanggan() {
        initComponents();
        Boolean currentIsCreateOrder = UserSession.getIsCreateOrder();

        if (currentIsCreateOrder == true) {
            labelMenu.setText("Daftar Pelanggan");
            buttonUbah.setVisible(false);
            buttonHapus.setVisible(false);
        }
        else {
            labelMenu.setText("Kelola Pelanggan");
            buttonKembali.setVisible(false);
        }
        tampil_table();
    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        pn_dasar = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        labelMenu = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePelanggan = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        buttonTutup = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        fieldIdPelanggan = new javax.swing.JTextField();
        fieldNama = new javax.swing.JTextField();
        fieldAlamat = new javax.swing.JTextField();
        fieldNoTelp = new javax.swing.JTextField();
        buttonTambah = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        cari = new javax.swing.JTextField();
        btn_cari = new javax.swing.JButton();
        fieldEmail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        buttonBersihkan = new javax.swing.JButton();
        buttonUbah = new javax.swing.JButton();
        buttonHapus = new javax.swing.JButton();
        buttonKembali = new javax.swing.JButton();

        jPanel7.setBackground(new java.awt.Color(205, 179, 149));
        jPanel7.setPreferredSize(new java.awt.Dimension(765, 137));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1121, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 143, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pn_dasar.setBackground(new java.awt.Color(255, 255, 255));
        pn_dasar.setPreferredSize(new java.awt.Dimension(1366, 773));

        jPanel1.setBackground(new java.awt.Color(255, 245, 238));

        jPanel8.setBackground(new java.awt.Color(255, 245, 238));
        jPanel8.setPreferredSize(new java.awt.Dimension(227, 768));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel12)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(597, 597, 597))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 815, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(205, 179, 149));
        jPanel2.setPreferredSize(new java.awt.Dimension(765, 137));

        labelMenu.setFont(new java.awt.Font("Myanmar Text", 1, 36)); // NOI18N
        labelMenu.setForeground(new java.awt.Color(255, 245, 238));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelMenu)
                .addGap(320, 320, 320))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(114, Short.MAX_VALUE)
                .addComponent(labelMenu)
                .addGap(29, 29, 29))
        );

        jPanel9.setBackground(new java.awt.Color(255, 245, 238));

        tablePelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nama", "Alamat", "Email", "No. Telepon"
            }
        ));
        tablePelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePelangganMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablePelanggan);

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(205, 179, 149));
        jLabel4.setText("Tabel Pelanggan");

        buttonTutup.setText("Tutup");
        buttonTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTutupActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(205, 179, 149));
        jLabel5.setText("ID Pelanggan :");

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(205, 179, 149));
        jLabel6.setText("Nama :");

        jLabel7.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(205, 179, 149));
        jLabel7.setText("Alamat : ");

        jLabel8.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(205, 179, 149));
        jLabel8.setText("No Telp : ");

        fieldIdPelanggan.setText("Otomatis Terisi");
        fieldIdPelanggan.setEnabled(false);
        fieldIdPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldIdPelangganActionPerformed(evt);
            }
        });

        buttonTambah.setText("Tambah");
        buttonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTambahActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(205, 179, 149));
        jLabel24.setText("Pencarian Pelanggan");

        btn_cari.setText("Search");
        btn_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cariActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(205, 179, 149));
        jLabel9.setText("Email:");

        buttonBersihkan.setText("Bersihkan");
        buttonBersihkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBersihkanActionPerformed(evt);
            }
        });

        buttonUbah.setText("Ubah");
        buttonUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUbahActionPerformed(evt);
            }
        });

        buttonHapus.setText("Hapus");
        buttonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHapusActionPerformed(evt);
            }
        });

        buttonKembali.setText("Kembali");
        buttonKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel24)
                    .addComponent(jLabel4)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_cari))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldIdPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(243, 243, 243)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldNoTelp, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(fieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 868, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(buttonBersihkan, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonTutup, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(220, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_cari, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(cari))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldNoTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldIdPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(87, 87, 87)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(buttonUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(buttonHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(buttonTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(buttonTutup, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(buttonBersihkan, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(buttonKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(124, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pn_dasarLayout = new javax.swing.GroupLayout(pn_dasar);
        pn_dasar.setLayout(pn_dasarLayout);
        pn_dasarLayout.setHorizontalGroup(
            pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_dasarLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1121, Short.MAX_VALUE)))
        );
        pn_dasarLayout.setVerticalGroup(
            pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_dasarLayout.createSequentialGroup()
                .addGroup(pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pn_dasarLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(pn_dasar, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTutupActionPerformed
        dispose();
        new Menu().setVisible(true);
    }//GEN-LAST:event_buttonTutupActionPerformed


    

    private void buttonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTambahActionPerformed
        Boolean currentIsCreateOrder = UserSession.getIsCreateOrder();
         if (currentIsCreateOrder == true) {
             try {
                 KelolaPesanan Bp = new KelolaPesanan();
                 String perm_jhtn = Bp.getPj();
                 String Hrg = Bp.getHrg();

                 if (Hrg == null || Hrg.trim().isEmpty()) {
                     JOptionPane.showMessageDialog(this, "Harga tidak boleh kosong");
                     return; 
                 }

                 double harga = Double.parseDouble(Hrg); 
                 String tgl_msk = Bp.getTm();
                 String tgl_k = Bp.getTk();
                 String Pgnrjn = Bp.getPngrjn();
                 String ktrg = Bp.getKet();

                 String nama = fieldNama.getText();
                 String noTelp = fieldNoTelp.getText();
                 String alamat = fieldAlamat.getText();
                 String email = fieldEmail.getText();

                 Connection Vconn = (Connection)Database.konfig(); 
                 int idPelanggan = -1;

  
                 String checkSql = "SELECT Id_Pelanggan FROM pelanggan WHERE Nama = ? AND No_Telp = ? AND Email = ? AND Alamat = ?";
                 PreparedStatement checkStmt = Vconn.prepareStatement(checkSql);
                 checkStmt.setString(1, nama);
                 checkStmt.setString(2, noTelp);
                 checkStmt.setString(3, email);
                 checkStmt.setString(4, alamat);
                 ResultSet rs = checkStmt.executeQuery();
                 if (rs.next()) {

                     idPelanggan = rs.getInt("Id_Pelanggan");
                 } else {
           
                     String insertSql = "INSERT INTO pelanggan (Nama, No_Telp, Email, Alamat) VALUES (?, ?, ?, ?)";
                     PreparedStatement insertStmt = Vconn.prepareStatement(insertSql, Statement.RETURN_GENERATED_KEYS);
                     insertStmt.setString(1, nama);
                     insertStmt.setString(2, noTelp);
                     insertStmt.setString(3, email);
                     insertStmt.setString(4, alamat);
                     int rowsInserted = insertStmt.executeUpdate();
                     if (rowsInserted > 0) {
                         rs = insertStmt.getGeneratedKeys();
                         if (rs.next()) {
                             idPelanggan = rs.getInt(1);
                         }
                     } else {
                         JOptionPane.showMessageDialog(null, "Tambah pelanggan gagal!");
                         return;
                     }
                 }

         
                 String sql = "INSERT INTO pesan_pelanggan (Permintaan_Jahitan, Harga, Tanggal_Masuk, Tanggal_Keluar, Pengerjaan, Keterangan, Id_Pelanggan) VALUES (?, ?, ?, ?, ?, ?, ?)";
                 PreparedStatement pstmt2 = Vconn.prepareStatement(sql);
                 pstmt2.setString(1, perm_jhtn);
                 pstmt2.setDouble(2, harga);
                 pstmt2.setString(3, tgl_msk);
                 pstmt2.setString(4, tgl_k);
                 pstmt2.setString(5, Pgnrjn);
                 pstmt2.setString(6, ktrg);
                 pstmt2.setInt(7, idPelanggan);
                 int rowsInserted = pstmt2.executeUpdate();
                 if (rowsInserted > 0) {
                     JOptionPane.showMessageDialog(null, "Berhasil ditambahkan"); 
                     dispose(); 
                     new KelolaPesanan().setVisible(true);
                 } else {
                     JOptionPane.showMessageDialog(null, "Tambah gagal!");
                 }                
             } catch (NumberFormatException e) {
                 JOptionPane.showMessageDialog(this, "Harga tidak valid: " + e.getMessage());
             } catch (Exception e) {
                 System.out.println(e.getMessage());
                 JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat menambahkan data: " + e.getMessage());
             }
         } else {
             try {
                 String nama = fieldNama.getText();
                 String noTelp = fieldNoTelp.getText();
                 String alamat = fieldAlamat.getText();
                 String email = fieldEmail.getText();

                 String sql = "INSERT INTO pelanggan (Nama, No_Telp, Email, Alamat) VALUES ('" + nama + "', '" + noTelp + "', '" + email + "', '" + alamat + "')";
                 Connection Vconn = (Connection)Database.konfig(); 
                 Statement stmt = Vconn.createStatement();
                 int rowsInserted = stmt.executeUpdate(sql);
                 if (rowsInserted > 0) {
                     JOptionPane.showMessageDialog(null, "Data berhasil ditambahkan!");
                     tampil_table();
                     bersih();
                 } else {
                     JOptionPane.showMessageDialog(null, "Data gagal ditambahkan!");
                 }
             } catch (Exception e) {
                 System.out.println(e.getMessage());
                 JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat menambahkan data: " + e.getMessage());
             }
         }     
    }//GEN-LAST:event_buttonTambahActionPerformed

    private void tablePelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePelangganMouseClicked
        // TODO add your handling code here:
        int baris = tablePelanggan.rowAtPoint(evt.getPoint());
        
        String idPelanggan = tablePelanggan.getValueAt(baris, 0).toString();
        fieldIdPelanggan.setText(idPelanggan);
        
        String nama = tablePelanggan.getValueAt(baris, 1).toString();
        fieldNama.setText(nama);
        
        String alamat = tablePelanggan.getValueAt(baris, 2).toString();
        fieldAlamat.setText(alamat);
            
        String email = tablePelanggan.getValueAt(baris, 3).toString();
        fieldEmail.setText(email);
        
        String noTelp = tablePelanggan.getValueAt(baris, 4).toString();
        fieldNoTelp.setText(noTelp);
        
    }//GEN-LAST:event_tablePelangganMouseClicked

    private void btn_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariActionPerformed
        // TODO add your handling code here:
        try{
            String query = "SELECT * FROM pelanggan WHERE " +
                       "id_pelanggan LIKE '%" + cari.getText() + "%' OR " +
                       "Nama LIKE '%" + cari.getText() + "%' OR " +
                       "No_Telp LIKE '%" + cari.getText() + "%' OR " +
                       "Email LIKE '%" + cari.getText() + "%' OR " +
                       "Alamat LIKE '%" + cari.getText() + "%'";
            java.sql.Connection vconn = (Connection) Database.konfig();
            java.sql.Statement s = vconn.createStatement();
            java.sql.ResultSet r = s.executeQuery(query);
            DefaultTableModel tb = new DefaultTableModel();
            tb.addColumn("ID");
            tb.addColumn("Nama");
            tb.addColumn("Alamat");
            tb.addColumn("Email");
            tb.addColumn("No. Telepon");
            int counter = 1;
            while (r.next()) {
                
                tb.addRow(new Object[]{
                    counter++,
                    r.getString("Nama"),
                    r.getString("Alamat"),
                    r.getString("Email"),
                    r.getString("No_Telp"),
                });
            }
            tablePelanggan.setModel(tb);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_cariActionPerformed

    private void buttonBersihkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBersihkanActionPerformed
        bersih();
    }//GEN-LAST:event_buttonBersihkanActionPerformed

    private void buttonKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKembaliActionPerformed
        dispose();
        new KelolaPesanan().setVisible(true);       
    }//GEN-LAST:event_buttonKembaliActionPerformed

    private void buttonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapusActionPerformed
        String idPelanggan = fieldIdPelanggan.getText();
        if (idPelanggan.equals("") || idPelanggan.equals("Otomatis Terisi")) {
            JOptionPane.showMessageDialog(null, "Pilih data terlebih dahulu!");
        } else {
            int confirm = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin menghapus data ini?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                try {
                    String Vsql = "DELETE FROM pelanggan WHERE Id_Pelanggan = ?";
                    java.sql.Connection vconn = (Connection) Database.konfig();
                    PreparedStatement pstmt = vconn.prepareStatement(Vsql);
                    pstmt.setString(1, idPelanggan);
                    int rowsDeleted = pstmt.executeUpdate();
                    if (rowsDeleted > 0) {
                        JOptionPane.showMessageDialog(null, "Hapus data berhasil!");
                        tampil_table();
                        bersih();
                    } else {
                        JOptionPane.showMessageDialog(null, "Hapus data gagal!");
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Terjadi error saat menghapus data:" + e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_buttonHapusActionPerformed

    private void buttonUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUbahActionPerformed
        String idPelanggan = fieldIdPelanggan.getText();
        String nama = fieldNama.getText();
        String email = fieldEmail.getText();
        String alamat = fieldAlamat.getText();
        String noTelp = fieldNoTelp.getText();

        if (idPelanggan.equals("") || idPelanggan.equals("Otomatis Terisi")) {
            JOptionPane.showMessageDialog(null, "Pilih data terlebih dahulu!");
        } else if (nama.equals("")) {
            JOptionPane.showMessageDialog(null, "Isi nama terlebih dahulu!");
        } else if (email.equals("")) {
            JOptionPane.showMessageDialog(null, "Isi email terlebih dahulu!");
        } else if (alamat.equals("")) {
            JOptionPane.showMessageDialog(null, "Isi alamat terlebih dahulu!");
        } else if (noTelp.equals("")) {
            JOptionPane.showMessageDialog(null, "Isi no telepon terlebih dahulu!");
        } else {
            try {
                String Vsql = "UPDATE pelanggan SET Nama = ?, No_Telp = ?, Email = ?, Alamat = ? WHERE Id_Pelanggan = ?";
                java.sql.Connection vconn = (Connection) Database.konfig();
                PreparedStatement pstmt = vconn.prepareStatement(Vsql);
                pstmt.setString(1, nama);
                pstmt.setString(2, noTelp);
                pstmt.setString(3, email);
                pstmt.setString(4, alamat);
                pstmt.setString(5, idPelanggan); 
                int rowsUpdated = pstmt.executeUpdate();
                if (rowsUpdated > 0) {
                    JOptionPane.showMessageDialog(null, "Ubah data berhasil!");
                    tampil_table();
                    bersih();
                } else {
                    JOptionPane.showMessageDialog(null, "Ubah data gagal!");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Terjadi error saat mengubah data:" + e.getMessage());
            }
        }
    }//GEN-LAST:event_buttonUbahActionPerformed

    private void fieldIdPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldIdPelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldIdPelangganActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cari;
    private javax.swing.JButton buttonBersihkan;
    private javax.swing.JButton buttonHapus;
    private javax.swing.JButton buttonKembali;
    private javax.swing.JButton buttonTambah;
    private javax.swing.JButton buttonTutup;
    private javax.swing.JButton buttonUbah;
    private javax.swing.JTextField cari;
    private javax.swing.JTextField fieldAlamat;
    private javax.swing.JTextField fieldEmail;
    private javax.swing.JTextField fieldIdPelanggan;
    private javax.swing.JTextField fieldNama;
    private javax.swing.JTextField fieldNoTelp;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelMenu;
    private javax.swing.JPanel pn_dasar;
    private javax.swing.JTable tablePelanggan;
    // End of variables declaration//GEN-END:variables

    private void tampil_table() {
        DefaultTableModel tb = new DefaultTableModel();
        tb.addColumn("ID");
        tb.addColumn("Nama");
        tb.addColumn("Alamat");
        tb.addColumn("Email");
        tb.addColumn("No. Telepon");
        
        try {
            String query = "SELECT * FROM pelanggan";
            java.sql.Connection vconn = (Connection) Database.konfig();
            java.sql.Statement s = vconn.createStatement();
            java.sql.ResultSet r = s.executeQuery(query);
            int counter = 1;
            while (r.next()) {
       
                tb.addRow(new Object[]{
                    r.getString("id_pelanggan"),
                    r.getString("Nama"),
                    r.getString("Alamat"),
                    r.getString("Email"),
                    r.getString("No_Telp"),
                });
            }
            tablePelanggan.setModel(tb);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void bersih() {
        fieldIdPelanggan.setText("Otomatis Terisi");
        fieldNama.setText("");
        fieldNoTelp.setText("");
        fieldAlamat.setText("");
        fieldEmail.setText("");
    }
    

}
