
package com.mycompany.ProjectUAS;

import com.mycompany.ProjectUAS.Menu;
import com.mycompany.ProjectUAS.Database;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Kelua
 */
public class Riwayat1 extends javax.swing.JFrame {

    /**
     * Creates new form Riwayat
     */
    public Riwayat1() {
        initComponents();
        tampilTabel();
        filter.add("Semua");
        filter.add("Selesai");
        filter.add("Ongoing");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_dasar = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_transaksi = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        carirt = new javax.swing.JTextField();
        cari = new javax.swing.JButton();
        filter = new java.awt.Choice();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pn_dasar.setBackground(new java.awt.Color(255, 255, 255));
        pn_dasar.setPreferredSize(new java.awt.Dimension(1366, 773));

        jPanel1.setBackground(new java.awt.Color(255, 245, 238));

        jPanel4.setBackground(new java.awt.Color(255, 245, 238));
        jPanel4.setPreferredSize(new java.awt.Dimension(227, 768));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel12)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(597, 597, 597))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 815, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(205, 179, 149));
        jPanel2.setPreferredSize(new java.awt.Dimension(765, 137));

        jLabel1.setFont(new java.awt.Font("Myanmar Text", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 245, 238));
        jLabel1.setText("RIWAYAT TRANSAKSI");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(219, 219, 219))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(34, 34, 34))
        );

        jPanel3.setBackground(new java.awt.Color(255, 245, 238));

        jt_transaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jt_transaksi);

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(205, 179, 149));
        jLabel3.setText("Tabel Data Riwayat Transaksi");

        jButton1.setText("Tutup");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(205, 179, 149));
        jLabel24.setText("Pencarian Data Riwayat Transaksi");

        cari.setText("Search");
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });

        filter.setFocusable(false);
        filter.setName(""); // NOI18N
        filter.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                filterItemStateChanged(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(205, 179, 149));
        jLabel6.setText("Filter: ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 868, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(carirt, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cari))
                            .addComponent(filter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cari, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(carirt))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(7, 7, 7)
                .addComponent(filter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(154, 154, 154)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pn_dasarLayout = new javax.swing.GroupLayout(pn_dasar);
        pn_dasar.setLayout(pn_dasarLayout);
        pn_dasarLayout.setHorizontalGroup(
            pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_dasarLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 913, Short.MAX_VALUE)))
        );
        pn_dasarLayout.setVerticalGroup(
            pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_dasarLayout.createSequentialGroup()
                .addGroup(pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pn_dasarLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(pn_dasar, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
        new Menu().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        // TODO add your handling code here:
                try {
    String query = "SELECT p.Tanggal_Masuk, pl.Nama, p.Permintaan_Jahitan, p.Harga, p.Keterangan " +
                   "FROM pelanggan pl " +
                   "JOIN pesan_pelanggan p ON pl.id_pelanggan = p.id_pelanggan " +
                   "WHERE pl.id_pelanggan LIKE '%" + carirt.getText() + "%' OR " +
                   "pl.Nama LIKE '%" + carirt.getText() + "%' OR " +
                   "pl.No_Telp LIKE '%" + carirt.getText() + "%' OR " +
                   "pl.Email LIKE '%" + carirt.getText() + "%' OR " +
                   "pl.Alamat LIKE '%" + carirt.getText() + "%'";
    java.sql.Connection vconn = (Connection) Database.konfig();
    java.sql.Statement s = vconn.createStatement();
    java.sql.ResultSet r = s.executeQuery(query);
    DefaultTableModel tb = new DefaultTableModel();
    tb.addColumn("Tanggal Masuk");
    tb.addColumn("Nama");
    tb.addColumn("Permintaan Jahitan");
    tb.addColumn("Harga");
    tb.addColumn("Keterangan");

    while (r.next()) {
        tb.addRow(new Object[]{
            r.getString("Tanggal_Masuk"),
            r.getString("Nama"),
            r.getString("Permintaan_Jahitan"),
            r.getInt("Harga"),
            r.getString("Keterangan")
        });
    }
    jt_transaksi.setModel(tb); 
    } catch (SQLException e) {
    }
    }//GEN-LAST:event_cariActionPerformed

    private void filterItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_filterItemStateChanged
        String selectedItem = (String) evt.getItem();
        
        if (selectedItem.equals("Semua")) {
            tampilTabel();

        } else if (selectedItem.equals("Selesai")) {
            try {
                String query = "SELECT p.Tanggal_Masuk, pl.Nama, p.Permintaan_Jahitan, p.Harga, p.Keterangan "
                             + "FROM pelanggan pl "
                             + "JOIN pesan_pelanggan p ON pl.id_pelanggan = p.id_pelanggan "
                             + "WHERE COALESCE(p.Tanggal_Keluar, '') != ''";

                java.sql.Connection vconn = (Connection) Database.konfig();
                java.sql.Statement s = vconn.createStatement();
                java.sql.ResultSet r = s.executeQuery(query);

                DefaultTableModel tb = new DefaultTableModel();
                tb.addColumn("Tanggal Masuk");
                tb.addColumn("Nama");
                tb.addColumn("Permintaan Jahitan");
                tb.addColumn("Harga");
                tb.addColumn("Keterangan");

                while (r.next()) {
                    tb.addRow(new Object[]{
                        r.getString("Tanggal_Masuk"),
                        r.getString("Nama"),
                        r.getString("Permintaan_Jahitan"),
                        r.getInt("Harga"),
                        r.getString("Keterangan")
                    });
                }
                jt_transaksi.setModel(tb);
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else if (selectedItem.equals("Ongoing")) {
            try {
                String query = "SELECT p.Tanggal_Masuk, pl.Nama, p.Permintaan_Jahitan, p.Harga, p.Keterangan "
                             + "FROM pelanggan pl "
                             + "JOIN pesan_pelanggan p ON pl.id_pelanggan = p.id_pelanggan "
                             + "WHERE COALESCE(p.Tanggal_Keluar, '') = ''";

                java.sql.Connection vconn = (Connection) Database.konfig();
                java.sql.Statement s = vconn.createStatement();
                java.sql.ResultSet r = s.executeQuery(query);

                DefaultTableModel tb = new DefaultTableModel();
                tb.addColumn("Tanggal Masuk");
                tb.addColumn("Nama");
                tb.addColumn("Permintaan Jahitan");
                tb.addColumn("Harga");
                tb.addColumn("Keterangan");

                while (r.next()) {
                    tb.addRow(new Object[]{
                        r.getString("Tanggal_Masuk"),
                        r.getString("Nama"),
                        r.getString("Permintaan_Jahitan"),
                        r.getInt("Harga"),
                        r.getString("Keterangan")
                    });
                }
                jt_transaksi.setModel(tb);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_filterItemStateChanged

    /**
     * @param args the command line arguments
     */
    
 private void tampilTabel() {
    DefaultTableModel tb = new DefaultTableModel();
    tb.addColumn("Tanggal Masuk");
    tb.addColumn("Nama");
    tb.addColumn("Permintaan Jahitan");
    tb.addColumn("Harga");
    tb.addColumn("Keterangan");

    try {
        String query = "SELECT p.Tanggal_Masuk, pl.Nama, p.Permintaan_Jahitan, p.Harga, p.Keterangan " +
                       "FROM pelanggan pl " +
                       "JOIN pesan_pelanggan p ON pl.id_pelanggan = p.id_pelanggan";
        java.sql.Connection vconn = (Connection) Database.konfig();
        java.sql.Statement s = vconn.createStatement();
        java.sql.ResultSet r = s.executeQuery(query);
        while (r.next()) {
            tb.addRow(new Object[]{
                r.getString("Tanggal_Masuk"),
                r.getString("Nama"),
                r.getString("Permintaan_Jahitan"),
                r.getInt("Harga"),
                r.getString("Keterangan")
            });
        }
        jt_transaksi.setModel(tb);
    } catch (Exception e) {
        e.printStackTrace();
    }
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cari;
    private javax.swing.JTextField carirt;
    private java.awt.Choice filter;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jt_transaksi;
    private javax.swing.JPanel pn_dasar;
    // End of variables declaration//GEN-END:variables
}
